[[questions]]
question_type_id = "multiple_answer"
tags = ["video_games"]
[questions.detail]
text = "Name the top 5 selling games for the Nintendo 64"
answer = [["Super Mario 64"], ["Mario Kart 64"], ["Golden Eye 007"], ["The Legend of Zelda: Ocarina of Time"], ["Super Smash Bros."]]

[[questions]]
question_type_id = "multiple_answer"
tags = ["video_games"]
[questions.detail]
text = "Who were the main characters in Donkey Kong Country 3?"
answer = [["Dixie Kong"], ["Kiddy Kong"]]

[[questions]]
question_type_id = "multiple_answer"
tags = ["video_games"]
[questions.detail]
text = "Name the 8 Pokemon with non-alphabetic characters in their name."
answer = [["Nidoran♀"], ["Nidoran♂"], ["Farfetch'd"], ["Mr. Mime"], ["Porygon2"], ["Ho-oh"], ["Mime Jr."], ["Porygon-Z"]]

[[questions]]
question_type_id = "multiple_answer"
tags = ["video_games"]
[questions.detail]
text = "Name the 16 Pokemon that appeared in Episode 1 of the Pokemon anime."
answer = [  ['Pikachu'],
            ['Nidorino'],
            ['Onix'],
            ['Gengar'],
            ['Spearow'],
            ['Ho-Oh', 'Ho Oh'],
            ['Bulbasaur'],
            ['Charmander'],
            ['Squirtle'],
            ['Pidgey'],
            ['Rattata'],
            ['Sandshrew'],
            ['Mankey'],
            ['Dodrio'],
            ['Magikarp'],
            ['Gyarados'],  ]
          
[[questions]]
question_type_id = "multiple_answer"
tags = ["video_games"]
[questions.detail]
text = "What are the only three Pokemon that can be obtained in every possible Pokeball?"
answer = [["Scyther"], ["Scizor"], ["Pinsir"],]
